// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseEchart: typeof import('./src/components/echarts-page/baseui/baseEchart.vue')['default']
    GradientStackedChart: typeof import('./src/components/echarts-page/src/gradientStackedChart.vue')['default']
    HorizontalBarChart: typeof import('./src/components/echarts-page/src/horizontalBarChart.vue')['default']
    ItemPage: typeof import('./src/components/echarts-page/baseui/itemPage.vue')['default']
    MapChart: typeof import('./src/components/echarts-page/src/mapChart.vue')['default']
    RoseChart: typeof import('./src/components/echarts-page/src/roseChart.vue')['default']
    StackedColumnChart: typeof import('./src/components/echarts-page/src/stackedColumnChart.vue')['default']
  }
}

export { }
